---
- hosts: "{{ hosts }}"
  become: true
  tasks:
    - name: get files
      block:
      - uri:
          url: "http://{{ item }}"
        with_items: 
        - linux01
        - linux02
        - linux03  
      rescue:
        - name: arranca apache"
          service:
            name: httpd
            state: started
      always:
        - debug:
            msg: "Siempre ejecuto esto"